version: "3.4"
volumes:
  astro_node_modules:

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - cloud-blender-api
      - cloud-blender-ui
    ports:
      - 7800:7800
  blender-api:
    build: blender-api
    image: blender-api
    restart: "no"
    volumes:
      - ./blender-api/:/app
      - "/var/run/docker.sock:/var/run/docker.sock"
    expose:
      - 7000
    depends_on:
      - database
      - redis
    env_file:
      - project.env
  cloud-blender-api:
    build: cloud-blender-api
    image: cloud-blender-api
    restart: "no"
    volumes:
      - ./cloud-blender-api/:/app
      - ./app-cache/:/app-cache
    expose:
      - 7777
    depends_on:
      - database
      - redis
      - blender-api
    env_file:
      - project.env
  cloud-blender-ui:
    build: cloud-blender-ui
    image: cloud-blender-ui
    restart: "no"
    volumes:
      - ./cloud-blender-ui/:/app
      - astro_node_modules:/app/node_modules
    expose:
      - 3000
    depends_on:
      - cloud-blender-api
  redis:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - 6379
  database:
    container_name: blender-database
    image: postgres:14.1
    restart: "no"
    env_file:
      - project.env
  flyway:
    image: flyway/flyway:9.11.0-alpine
    depends_on:
      - database
    volumes:
      - ./flyway/sql/:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env
    
